name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      - name: "Start testing containers"
        run: docker-compose up -d
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci
      - run: npm config -g set access public
      - run: npm run baum-publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          PUBLISH_VERSION: ${{ github.event.release.tag_name }}
          NPM_CONFIG_PROVENANCE: true
      - name: json schema
        run: |
          mkdir -p $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}
          mv $GITHUB_WORKSPACE/steps/installer/renderer/schema.json $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}/schema.json
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}/schema.json
          git commit -m "helm schema for version ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
