name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm config -g set access public
      - run: npm run baum
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          PUBLISH_VERSION: ${{ github.event.release.tag_name }}
          NPM_CONFIG_PROVENANCE: true
      - name: json schema
        run: |
          mkdir -p $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}
          mv $GITHUB_WORKSPACE/steps/helm/out.json $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}/schema.json
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add $GITHUB_WORKSPACE/docs/schema/steps/helm/${{ github.event.release.tag_name }}/schema.json
          git commit -m "helm schema for version ${{ github.event.release.tag_name }}"
          git push origin HEAD:main
