name: testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: 'v3'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: testing
        run: npm run baum
        env:
          CI_TEST: true
        
