name: testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        version: [18, 20, 22, 24]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      - name: "Start testing containers"
        run: docker-compose up -d
      - uses: azure/setup-helm@v4
        with:
          version: 'latest'
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci
      - name: testing
        run: npm run baum-test
        env:
          CI_TEST: true
        
