name: testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    #services:
    #  verdaccio:
    #    image: verdaccio/verdaccio
    #    volumes: 
    #      # - /steps/docker/verdaccio/config.yaml:/verdaccio/conf/config.yaml
    #    ports:
    #      - 4873:4873
    steps:
      - uses: actions/checkout@v4
      - uses: docker://docker
      - name: "Start testing containers"
        run: docker-compose  
      - uses: azure/setup-helm@v4
        with:
          version: 'latest'
      # - uses: addnab/docker-run-action@v3
      #   with:
      #     image: verdaccio/verdaccio
      #     options: -d --name -p 4873:4873
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: testing
        run: npm run baum
        env:
          CI_TEST: true
        
